author:
  name: DigitalChip
  email: xsidmail@domain.com
title: "Заметки"
description: "Короткие заметки о технологиях и IT"

remote_theme: jekyll/minima@d4d779a
minima:
  skin: solarized
  
  date_format: "%Y-%m-%d"
    # Социальные ссылки
  social_links:
    twitter: dchiper
    github: DigitaChip
    
  # Настройки постов
  post:
    excerpt_separator: "<!--читать-->"
  
  # Кодировка
  encoding: UTF-8
  
  # Настройки SEO
  seo:
    title: true
    description: true
    author: true